# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                   Command:    7 /    4 = 175.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'flexmock'
class Engine
  @@mock = FlexMock.new
  @@mock.mock_handle(:db) {@@mock}
  @@mock.mock_handle(:mark) {}
  @@mock.mock_handle(:getid) {$id += 1}
  @@mock.mock_handle(:get) do |oid|
    case oid
    when 0 then @@mock
    end
  end
  def self.instance
    @@mock
  end
end

require 'storage/properties'
require 'core/player'
require 'command'
end

class TestCommand < Test::Unit::TestCase
  def setup
    $id = 0
    @c = Command.new(:cmd, "name", "help")
  end

  def test_cmd
    assert_equal(:cmd, @c.cmd)
  end

  def test_name
    assert_equal("name", @c.name)
  end

  def test_help
    assert_equal("help", @c.help)
  end

  def test_singleton_Command_load
    c, o = Command.load
    assert(true,c && o)
    a = GameObject.new("testthing",0)
    assert_respond_to(a,:ocmd_echoat)
    assert(true, c.insert(@c.name, @c))
    assert_equal(@c, c.find_exact(@c.name))
  end
end

