# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                  PacketIO:    2 /    3 =  66.67%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'net/packetio'
require 'flexmock'
class FlexMock
  undef_method(:send)
  rescue NameError
end
end

class TestPacketIO < Test::Unit::TestCase
  def setup
    @data = ["hello world\000".size].pack("N") + "hello world\000foobar"
    sock = FlexMock.new
    sock.mock_handle(:recv) { |bufsize,flag| @data.slice!(0...bufsize) }
    sock.mock_handle(:send) { |msg,flag| msg.size }
    @sock = PacketIO.new(sock)
  end

  def test_read
    assert_equal("hello world", @sock.read)
  end

  def test_write
    assert_equal(true, @sock.write("hello world\r\n"))
  end
end

