# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                  Database:   27 /   10 = 270.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'db/database'
require 'flexmock'
require 'ostruct'
require 'db/player'
require 'db/room'
end

class TestDatabase < Test::Unit::TestCase
  def setup
    @log = FlexMock.new
    @log.mock_handle(:info) { |msg| puts msg }
    @log.mock_handle(:debug) { |msg| puts msg }
    @log.mock_handle(:warn) { |msg| puts msg }
    @log.mock_handle(:error) { |msg| puts msg }
    myopts = OpenStruct.new
    myopts.dbname = "testdb"
    @db = Database.new(@log, myopts)
    $engine = FlexMock.new
    $engine.mock_handle(:world) {$engine}
    $engine.mock_handle(:options) {$engine}
    $engine.mock_handle(:home) {1}
    $engine.mock_handle(:db) {@db}
    @r = Room.new("Here")
    @o = GameObject.new("Thing")
    @p = Player.new("Tyche", "tyche", nil)
  end

  def teardown
    File.delete("testdb")
  end

  def test_delete
    assert_equal(@r, @db.put(@r))
    assert_equal(@o, @db.put(@o))
    assert_equal(@r, @db.delete(@r.oid))
    assert_equal(@o, @db.delete(@o.oid))
    assert_equal(nil, @db.delete(@p.oid))
  end

  def test_find_player_by_name
    assert_equal(@p, @db.put(@p))
    assert_equal(@p, @db.find_player_by_name("Tyche"))
    assert_equal(nil, @db.find_player_by_name("Bubba"))
  end

  def test_get
    assert_equal(@r, @db.put(@r))
    assert_equal(@o, @db.put(@o))
    assert_equal(@r, @db.get(@r.oid))
    assert_equal(@o, @db.get(@o.oid))
    assert_equal(nil, @db.get(@p.oid))
  end

  def test_getid
    assert_equal(5,@db.getid)
  end

  def test_objects
    assert_equal(@r, @db.put(@r))
    assert_equal(@o, @db.put(@o))
    assert_equal(@p, @db.put(@p))
    cnt = 0
    @db.objects {cnt += 1}
    assert_equal(4,cnt)
  end

  def test_players_connected
    assert(@db.players_connected)
  end

  def test_put
    assert_equal(@r, @db.put(@r))
    assert_equal(@o, @db.put(@o))
    assert_equal(@p, @db.put(@p))
  end

  def test_save
    assert(@db.save)
  end

  def test_stats
    assert_equal(@r, @db.put(@r))
    assert_equal(@o, @db.put(@o))
    assert_equal(@p, @db.put(@p))
    stats=<<EOH
[COLOR=cyan]
---* Database Statistics *---
  Rooms   - 2
  Players - 1
  Objects - 1
  Total Objects - 4
  Highest OID in use - 4
---*                     *---
[/COLOR]
EOH
    assert_equal(stats,@db.stats)
  end
end

