# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                   Command:    7 /    4 = 175.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'flexmock'
require 'command'
require 'db/properties'
require 'db/player'
end

class TestCommand < Test::Unit::TestCase
  def setup
    @c = Command.new(:cmd, "name", "help")
    @nextid = 0
    $engine = FlexMock.new
    $engine.mock_handle(:world) {$engine}
    $engine.mock_handle(:db) {$engine}
    $engine.mock_handle(:check) {false}
    $engine.mock_handle(:getid) {@nextid += 1}
  end

  def test_cmd
    assert_equal(:cmd, @c.cmd)
  end

  def test_name
    assert_equal("name", @c.name)
  end

  def test_help
    assert_equal("help", @c.help)
  end

  def test_singleton_Command_load
    c, o = Command.load
    assert(true,c && o)
    a = GameObject.new("testthing")
    assert_respond_to(a,:ocmd_echoat)
    assert(true, c.insert(@c.name, @c))
    assert_equal(@c, c.find_exact(@c.name))
  end
end

