# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                GameObject:    0 /   13 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestGameObject < Test::Unit::TestCase
  def test_add_contents
    raise NotImplementedError, 'Need to write test_add_contents'
  end

  def test_add_trigger
    raise NotImplementedError, 'Need to write test_add_trigger'
  end

  def test_ass
    raise NotImplementedError, 'Need to write test_ass'
  end

  def test_delete_contents
    raise NotImplementedError, 'Need to write test_delete_contents'
  end

  def test_delete_trigger
    raise NotImplementedError, 'Need to write test_delete_trigger'
  end

  def test_desc
    raise NotImplementedError, 'Need to write test_desc'
  end

  def test_desc_equals
    raise NotImplementedError, 'Need to write test_desc_equals'
  end

  def test_fart
    raise NotImplementedError, 'Need to write test_fart'
  end

  def test_get_contents
    raise NotImplementedError, 'Need to write test_get_contents'
  end

  def test_get_trigger
    raise NotImplementedError, 'Need to write test_get_trigger'
  end

  def test_get_triggers
    raise NotImplementedError, 'Need to write test_get_triggers'
  end

  def test_location
    raise NotImplementedError, 'Need to write test_location'
  end

  def test_location_equals
    raise NotImplementedError, 'Need to write test_location_equals'
  end

  def test_name_equals
    raise NotImplementedError, 'Need to write test_name_equals'
  end

  def test_objects
    raise NotImplementedError, 'Need to write test_objects'
  end

  def test_oid
    raise NotImplementedError, 'Need to write test_oid'
  end

  def test_oid_equals
    raise NotImplementedError, 'Need to write test_oid_equals'
  end

  def test_parse
    raise NotImplementedError, 'Need to write test_parse'
  end

  def test_players
    raise NotImplementedError, 'Need to write test_players'
  end

  def test_powered
    raise NotImplementedError, 'Need to write test_powered'
  end

  def test_powered_equals
    raise NotImplementedError, 'Need to write test_powered_equals'
  end
end

# Number of errors detected: 1
