# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                 Connector:    3 /    3 = 100.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'net/connector'
require 'flexmock'
end

class TestConnector < Test::Unit::TestCase
  def setup
    @log = FlexMock.new
    @log.mock_handle(:info) { |msg| puts msg }
    @log.mock_handle(:debug) { |msg| puts msg }
    @log.mock_handle(:warn) { |msg| puts msg }
    @log.mock_handle(:error) { |msg| puts msg }
    @serv = FlexMock.new
    @serv.mock_handle(:log) { @log }
    @serv.mock_handle(:register) { true }
    @connector = Connector.new(@serv,80,[:client, :filter, :sockio],'google.com')
  end

  def test_handle_close
    assert_respond_to(@connector, :handle_close)
  end

  def test_init
    assert_equal(true, @connector.init)
  end
end

