# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                    LineIO:    4 /    2 = 200.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'net/lineio'
require 'flexmock'
class FlexMock
  undef_method(:send)
  rescue NameError
end
end

class TestLineIO < Test::Unit::TestCase
  def setup
    @data = "hello world\r\nfoobar"
    sock = FlexMock.new
    sock.mock_handle(:recv) { |bufsize,flag| @data.slice!(0...bufsize) }
    sock.mock_handle(:send) { |msg,flag| msg.size }
    @sock = LineIO.new(sock, 5)
  end

  def test_read
    assert_equal(nil, @sock.read)
    assert_equal(nil, @sock.read)
    assert_equal("hello world\n", @sock.read)
    assert_equal(nil, @sock.read)
  end

end

