# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                      Room:    0 /    2 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestRoom < Test::Unit::TestCase
  def test_ass
    raise NotImplementedError, 'Need to write test_ass'
  end

  def test_exits
    raise NotImplementedError, 'Need to write test_exits'
  end

  def test_exits_equals
    raise NotImplementedError, 'Need to write test_exits_equals'
  end
end

# Number of errors detected: 1
